/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMyProjectArgs } from "./CreateMyProjectArgs";
import { UpdateMyProjectArgs } from "./UpdateMyProjectArgs";
import { DeleteMyProjectArgs } from "./DeleteMyProjectArgs";
import { MyProjectFindManyArgs } from "./MyProjectFindManyArgs";
import { MyProjectFindUniqueArgs } from "./MyProjectFindUniqueArgs";
import { MyProject } from "./MyProject";
import { User } from "../../user/base/User";
import { MyProjectService } from "../myProject.service";

@graphql.Resolver(() => MyProject)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MyProjectResolverBase {
  constructor(
    protected readonly service: MyProjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "read",
    possession: "any",
  })
  async _myProjectsMeta(
    @graphql.Args() args: MyProjectFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [MyProject])
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "read",
    possession: "any",
  })
  async myProjects(
    @graphql.Args() args: MyProjectFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MyProject[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MyProject",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => MyProject, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "read",
    possession: "own",
  })
  async myProject(
    @graphql.Args() args: MyProjectFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MyProject | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "MyProject",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => MyProject)
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "create",
    possession: "any",
  })
  async createMyProject(
    @graphql.Args() args: CreateMyProjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MyProject> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "MyProject",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MyProject"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => MyProject)
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "update",
    possession: "any",
  })
  async updateMyProject(
    @graphql.Args() args: UpdateMyProjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MyProject | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "MyProject",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MyProject"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MyProject)
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "delete",
    possession: "any",
  })
  async deleteMyProject(
    @graphql.Args() args: DeleteMyProjectArgs
  ): Promise<MyProject | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MyProject",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: MyProject,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
