/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { MyProjectWhereInput } from "./MyProjectWhereInput";
import { Type } from "class-transformer";
import { MyProjectOrderByInput } from "./MyProjectOrderByInput";

@ArgsType()
class MyProjectFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => MyProjectWhereInput,
  })
  @Field(() => MyProjectWhereInput, { nullable: true })
  @Type(() => MyProjectWhereInput)
  where?: MyProjectWhereInput;

  @ApiProperty({
    required: false,
    type: MyProjectOrderByInput,
  })
  @Field(() => MyProjectOrderByInput, { nullable: true })
  @Type(() => MyProjectOrderByInput)
  orderBy?: MyProjectOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { MyProjectFindManyArgs };
